logging.config=file:config/log4j2.xml

# SSL
gnoolson.saturday.server.ssl=false

# Server
server.port=5050
server.tomcat.max-threads=8
server.servlet.session.timeout=60m

# Spring
spring.main.allow-bean-definition-overriding=true
spring.jmx.enabled=false

# Thymeleaf
spring.thymeleaf.prefix=file:web/templates/
spring.thymeleaf.cache=false

# H2
h2.db_server.port=19880
h2.web_server.port=5052

# JPA / Hibernate
spring.datasource.driver_class_name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost:19880/./data/saturday;DB_CLOSE_ON_EXIT=FALSE;
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_query_cache=false
spring.jpa.properties.hibernate.use_second_level_cache=false

# Project
gnoolson.saturday.web.messages.path=file:web/messages/
gnoolson.saturday.web.static.path=file:web/static/

# Project. Dashboard
gnoolson.saturday.dashboard.static=file:dashboard_static/
gnoolson.saturday.dashboard.template=file:template/default/dashboard.html

# Project. Script
gnoolson.saturday.script.max_errors=50
gnoolson.saturday.script.template=file:template/default/script.lua
gnoolson.saturday.script.lua.full_access=true
gnoolson.saturday.script.lua.max_execution_time=10000
gnoolson.saturday.script.lua.beautify_code.stylua_folder=file:lib/
gnoolson.saturday.script.lua.lib=file:lualib/
gnoolson.saturday.script.sandbox_storage.clean_interval=5
gnoolson.saturday.script.cache.status_flag.storage_time=30
gnoolson.saturday.script.cache.status_flag.clean_interval=5

# Project. Script. Log
gnoolson.saturday.script.log_storage.path=file:log/scripts/
gnoolson.saturday.script.log.cache.clean_interval=5
gnoolson.saturday.script.log.cache.storage_time=300

# Project. Plugin
gnoolson.saturday.plugin.path=file:plugins/

# Project. Demo
gnoolson.saturday.ie.demo=file:demo/

# Project. Users
gnoolson.saturday.users.storage_file=file:data/users